# Generated by Django 5.0 on 2025-09-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_github_profile_linkedin_profile_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects_text',
            field=models.TextField(blank=True, help_text='Describe your notable projects, technologies used, and impact.'),
        ),
    ]
