# Generated by Django 4.2.24 on 2025-09-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobseekerprofile_workexperience_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='JobSeekerProfile',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
