# Generated by Django 4.2.24 on 2025-09-25 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(default='No experience info'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.TextField(default='No education info'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(default='No headline yet', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='links',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(default='No skills listed'),
        ),
    ]
