# Generated by Django 5.0 on 2025-09-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for recruiters', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('applied', 'Applied'), ('review', 'Under Review'), ('interview', 'Interview'), ('offer', 'Offer')], default='applied', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
